name: deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x.x

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install make wget tar

      - name: Get WASI SDK 20.0
        run: |
          wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-20/wasi-sdk-20.0-linux.tar.gz
          tar xzf wasi-sdk-20.0-linux.tar.gz

      - name: Build wasm binaries
        run: make demo -B
        env: 
          WASI_SDK_PATH: ./wasi-sdk-20.0/

      - name: Build Vite app
        working-directory: demo
        run: |
          npm install
          npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: demo/dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
